In [6]:
import pandas as pd
import numpy as np
import pickle
pd.set_option('display.max_columns', None)

In [7]:
%%time
smileon = pd.read_pickle("../data/smileon.pkl")

Wall time: 295 ms


In [8]:
smileon.head(2)

CallReportNum              ReportVersion LinkedToCallReportNum  \
0       93115324  SMILE ON 60+ Registration                   NaN   
1       93115188  SMILE ON 60+ Registration                   NaN   

  CallDateAndTimeStart CallDateAndTimeEnd  CallLength  CallerNum  \
0      9/30/2021 16:56    9/30/2021 16:57           1    3638169   
1      9/30/2021 16:53    9/30/2021 16:53           0    4431194   

   PhoneWorkerNum   CityName  CountyName StateProvince    CountryName  \
0          123747     Smyrna  Rutherford            TN  United States   
1          123747  Nashville    Davidson            TN  United States   

   PostalCode PhoneType ThirdPartyStateProvince  \
0     37167.0    Mobile                     NaN   
1     37211.0       NaN                     NaN   

                                           Narrative Feedback  \
0  spoke with client again concerning transfer to...      NaN   
1  Called client to follow up on app. LM for call...      NaN   

   EnteredByWorkerNum        EnteredOn Reviewed FeedbackStatus  \
0              123747  9/30/2021 16:57       No        Not yet   
1              123747  9/30/2021 16:53       No        Not yet   

   FeedbackFromPhoneWorkerNum FeedbackFromPhoneWorkerName ReferralsMade  \
0                         NaN                         NaN           NaN   
1                         NaN                         NaN           NaN   

   OrgNum Demo_# of People in Household Birth Year Demo_Other Language  \
0   51426                           1.0       1960                 NaN   
1   51426                           1.0       1959                 NaN   

  Notes (Optional) - Notes  OralCare_1351  OralCare_1354  OralCare_2140  \
0                      NaN            NaN            NaN            NaN   
1                      NaN            NaN            NaN            NaN   

   OralCare_2150  OralCare_2160  OralCare_2161  OralCare_230  OralCare_2330  \
0            NaN            NaN            NaN           NaN            NaN   
1            NaN            NaN            NaN           NaN            NaN   

   OralCare_2331  OralCare_2332  OralCare_2335  OralCare_2390  OralCare_2391  \
0            NaN            NaN            NaN            NaN            NaN   
1            NaN            NaN            NaN            NaN            NaN   

   OralCare_2392 OralCare_2393  OralCare_2394  OralCare_2915  OralCare_2920  \
0            NaN           NaN            NaN            NaN            NaN   
1            NaN           NaN            NaN            NaN            NaN   

   OralCare_2933  OralCare_2940 OralCare_2950  OralCare_2954  OralCare_2980  \
0            NaN            NaN           NaN            NaN            NaN   
1            NaN            NaN           NaN            NaN            NaN   

   OralCare_3220  OralCare_4341 OralCare_4342  OralCare_6930  OralCare_6980  \
0            NaN            NaN           NaN            NaN            NaN   
1            NaN            NaN           NaN            NaN            NaN   

   OralCare_7111 OralCare_7140  OralCare_7210  OralCare_7220  OralCare_7230  \
0            NaN           NaN            NaN            NaN            NaN   
1            NaN           NaN            NaN            NaN            NaN   

   OralCare_7240  OralCare_7241  OralCare_7250  OralCare_7261  OralCare_7286  \
0            NaN            NaN            NaN            NaN            NaN   
1            NaN            NaN            NaN            NaN            NaN   

   OralCare_7310  OralCare_7311 OralCare_7320  OralCare_7321  OralCare_7410  \
0            NaN            NaN           NaN            NaN            NaN   
1            NaN            NaN           NaN            NaN            NaN   

   OralCare_7411  OralCare_7471  OralCare_7510  OralCare_7971  OralCare_7972  \
0            NaN            NaN            NaN            NaN            NaN   
1            NaN            NaN            NaN            NaN            NaN

In [18]:
gtc =smileon[['CallReportNum', 'CallerNum', 'ReferralsMade', 'OrgNum', 'Screen_Last Screening Date', 
             'Baseline_Are you limited in what you can eat?', 'Baseline_Did the client commit to referral?', 
             'Baseline_Have you ever felt that the appearance of your mouth and teeth affected your quality of life?', 
             'Baseline_How would you describe the condition of your mouth and teeth?', 
             'CM_What is the outcome for the client?', 'Clinic_Was initial appointment made?', 
             'Screen_Experienced any problems related to mouth/teeth during past 12 months?', 
             'TPlan_Is the treatment plan completed?', 
             'TPlan_Was the enrollee able to be restored to function (can chew) and "social six" esthetics (top front six teeth are present and disease free)' ]]

In [19]:
gtc.head(2)

CallReportNum  CallerNum  OrgNum ReferralsMade  OrgNum  \
0       93115324    3638169   51426           NaN   51426   
1       93115188    4431194   51426           NaN   51426   

  Screen_Last Screening Date Baseline_Are you limited in what you can eat?  \
0                        NaN                                           Yes   
1                        NaN                                           Yes   

  Baseline_Did the client commit to referral?  \
0                                         Yes   
1                                         Yes   

  Baseline_Have you ever felt that the appearance of your mouth and teeth affected your quality of life?  \
0                                                Yes                                                       
1                                                Yes                                                       

  Baseline_How would you describe the condition of your mouth and teeth?  \
0                                               Poor                       
1                                               Poor                       

  CM_What is the outcome for the client? Clinic_Was initial appointment made?  \
0                                    NaN                                  NaN   
1                                    NaN                                  NaN   

  Screen_Experienced any problems related to mouth/teeth during past 12 months?  \
0                                                NaN                              
1                                                NaN                              

  TPlan_Is the treatment plan completed?  \
0                                    NaN   
1                                    NaN   

  TPlan_Was the enrollee able to be restored to function (can chew) and "social six" esthetics (top front six teeth are present and disease free)  
0                                                NaN                                                                                               
1                                                NaN

In [24]:
gtc['CallReportNum'].nunique()

57860

In [27]:
gtc['CallerNum'].nunique() #10,000 callers for 57,000 rows of dta

10711

In [28]:
gtc['OrgNum'].nunique()

OrgNum    1
OrgNum    1
dtype: int64

In [30]:
#gtc['Screen_Last Screening Date'].unique() #DO I NEED TO CALCULATE NUMBER OF DAYS BETWEEN CALL AND LAST SCREENING DATE

array([nan, '10/8/2019', '11/10/2020', '9/10/2021', '9/10/2019',
       '10/6/2021', '3/8/2021', '5/20/2021', '8/26/2020', '9/30/2021',
       '1/12/2021', '10/2/2019', '8/24/2021', '6/13/2019', '3/1/2021',
       '3/23/2021', '6/10/2021', '7/14/2021', '9/23/2021', '11/30/2020',
       '9/9/2021', '9/29/2021', '1/21/2021', '9/8/2021', '2/3/2021',
       '3/16/2021', '3/15/2021', '10/8/2018', '8/12/2021', '3/2/2020',
       '6/28/2021', '4/22/2021', '4/12/2021', '9/28/2021', '8/11/2021',
       '1/13/2021', '7/19/2021', '5/13/2021', '5/17/2021', '3/25/2021',
       '1/5/2021', '10/1/2018', '12/15/2020', '10/26/2020', '2/2/2021',
       '7/8/2021', '1/2/2020', '8/31/2021', '5/3/2021', '9/1/2021',
       '6/10/2019', '3/22/2021', '9/27/2021', '1/19/2021', '6/24/2021',
       '9/16/2020', '5/18/2021', '2/6/2020', '8/27/2021', '10/19/2020',
       '9/24/2021', '9/22/2021', '4/30/2021', '8/13/2021', '3/28/2019',
       '7/27/2021', '8/19/2021', '3/5/2020', '8/9/2021', '2/4/2021',
       '8/1

In [34]:
gtc['Baseline_Are you limited in what you can eat?'].unique()

array(['Yes', 'No', nan], dtype=object)

In [32]:
gtc['Baseline_How would you describe the condition of your mouth and teeth?'].unique()

array(['Poor', 'Good', 'Fair', 'Dont know', nan, 'Very Good'],
      dtype=object)

In [33]:
gtc['CM_What is the outcome for the client?'].unique()

array([nan, 'Navigation to dental clinic for dental exam and treatment',
       'Enrolled in Wisdom Tooth Project Workshop'], dtype=object)

In [35]:
gtc['Clinic_Was initial appointment made?'].unique()

array([nan, 'Yes', 'No'], dtype=object)

In [36]:
gtc['Screen_Experienced any problems related to mouth/teeth during past 12 months?'].unique()

array([nan,
       'Difficulty when biting or chewing foods; Experienced pain or discomfort',
       'Difficulty when biting or chewing foods; Difficulty with speech or pronouncing words; Experienced pain or discomfort',
       'Difficulty when biting or chewing foods; Difficulty with speech or pronouncing words; Avoided smiling',
       'Felt anxiety; Avoided smiling',
       'Difficulty when biting or chewing foods; Felt anxiety; Experienced pain or discomfort',
       'Difficulty when biting or chewing foods; Difficulty with speech or pronouncing words; Dry mouth; Felt anxiety; Felt embarrassement; Avoided smiling',
       'Difficulty when biting or chewing foods; Felt anxiety; Felt embarrassement; Avoided smiling; Experienced pain or discomfort',
       'Difficulty when biting or chewing foods',
       'Difficulty when biting or chewing foods; Difficulty with speech or pronouncing words; Dry mouth; Felt anxiety; Felt embarrassement; Avoided smiling; Experienced pain or discomfort',

In [40]:
gtc['TPlan_Is the treatment plan completed?'].unique()

array([nan, 'No', 'Yes'], dtype=object)

In [41]:
gtc['TPlan_Was the enrollee able to be restored to function (can chew) and "social six" esthetics (top front six teeth are present and disease free'].unique()

KeyError: 'TPlan_Was the enrollee able to be restored to function (can chew) and "social six" esthetics (top front six teeth are present and disease free'